CREATE SCHEMA IF NOT EXISTS "SMP";

CREATE TABLE IF NOT EXISTS SMP.T_PERSONS(
    id INT PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    id_number VARCHAR(20) NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS SMP.S_PERSONS_SEQ START WITH 100 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS SMP.T_USERS_DETAILS(
    id INT PRIMARY KEY,
    person_id INT NOT NULL,
    user_name VARCHAR(20) NOT NULL UNIQUE,
    secure_token VARCHAR(20) NOT NULL UNIQUE
);

ALTER TABLE SMP.T_USERS_DETAILS ADD CONSTRAINT IF NOT EXISTS SMP.USER_NAME_SEC_TOKEN_CON UNIQUE(user_name, secure_token);

ALTER TABLE SMP.T_USERS_DETAILS ADD CONSTRAINT IF NOT EXISTS SMP.USERS_DETAILS_PERSON_FK FOREIGN KEY(person_id) REFERENCES SMP.T_PERSONS(id);

CREATE SEQUENCE IF NOT EXISTS SMP.S_USERS_DETAILS_SEQ START WITH 100 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS SMP.T_DEPARTMENTS(
    id INT PRIMARY KEY,
    dept_number VARCHAR(10) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE SEQUENCE IF NOT EXISTS SMP.S_DEPARTMENTS_SEQ START WITH 100 INCREMENT BY 1;


CREATE TABLE IF NOT EXISTS SMP.T_TEACHING_STAFF(
    id INT PRIMARY KEY,
    teaching_staff_member_type VARCHAR(20) NOT NULL,
    dept_id INT NOT NULL
);

ALTER TABLE SMP.T_TEACHING_STAFF ADD CONSTRAINT SMP.TEACH_STAFF_PERSON_FK FOREIGN KEY(id) REFERENCES SMP.T_PERSONS(id);

ALTER TABLE SMP.T_TEACHING_STAFF ADD CONSTRAINT SMP.TEACH_STAFF_DEPT_FK FOREIGN KEY(dept_id) REFERENCES SMP.T_DEPARTMENTS(id);


CREATE TABLE IF NOT EXISTS SMP.T_ADMIN_STAFF(
    id INT PRIMARY KEY,
    staff_member_number VARCHAR(20) NOT NULL UNIQUE,
    admin_staff_member_type VARCHAR(20) NOT NULL,
    dept_id INT NOT NULL
);

ALTER TABLE SMP.T_ADMIN_STAFF ADD CONSTRAINT SMP.ADMIN_STAFF_PERSON_FK FOREIGN KEY(id) REFERENCES SMP.T_PERSONS(id);


CREATE TABLE IF NOT EXISTS SMP.T_ALUMNI_MEMBERS(
    id INT PRIMARY KEY,
    alumni_member_number VARCHAR(20) NOT NULL UNIQUE
);

ALTER TABLE SMP.T_ALUMNI_MEMBERS ADD CONSTRAINT SMP.ALUMNI_MEMBERS_PERSON_FK FOREIGN KEY(id) REFERENCES SMP.T_PERSONS(id);
